import type { DentalDashboardData, DentalLead, TreatmentKey } from "@/lib/dental-types";

export const treatmentLabels: Record<TreatmentKey, string> = {
  invisalign: "Invisalign",
  implants: "Implants",
  full_arch_implants: "Full arch implants",
  composites: "Composite bonding",
  whitening: "Whitening",
  veneers: "Veneers",
  hygiene: "Hygiene",
  emergency: "Emergency",
};

export const defaultAgentPrompt = `You are the WhatsApp assistant for a dental practice.

Stay warm, concise, and practical. Qualify the patient, answer from the approved knowledge, and move toward a consultation only when it is appropriate.

Do not diagnose. Do not guarantee treatment, price, finance approval, or clinical outcomes. Escalate complaints, medical uncertainty, pricing disputes, and anything sensitive to staff.`;

export const defaultFirstMessage =
  "Hi {{first_name}}, it is {{practice_name}}. We noticed you were interested in {{treatment}}. Would you like me to help you find a suitable consultation slot?";

const now = Date.now();
const minutesAgo = (minutes: number) => new Date(now - minutes * 60_000).toISOString();

export const mockDentalLeads: DentalLead[] = [
  {
    id: "mock-ruth",
    practiceId: "mock-practice",
    name: "Ruth Derham",
    phone: "+447700900123",
    email: "ruth@example.com",
    treatment: "invisalign",
    status: "engaged",
    source: "boxly",
    sourceSystem: "regent",
    boxName: "Invisalign",
    boxStage: "AI actioned",
    needsHuman: false,
    aiConfidence: 0.82,
    aiActioned: true,
    actioned: true,
    clientReplied: true,
    unseenReplyCount: 1,
    conversationCount: 12,
    leadSummary: "Asked about Invisalign consultation availability.",
    urgency: "warm",
    actionedNote: "AI re-engagement sent and patient replied with availability.",
    entryPoint: "https://regentdental.co.uk/invisalign",
    actionedAt: minutesAgo(46),
    aiActionedAt: minutesAgo(46),
    becameLeadAt: minutesAgo(1440),
    lastUpdatedAt: minutesAgo(3),
    scrapedAt: minutesAgo(2),
    lastSyncedAt: minutesAgo(2),
    updatedAt: minutesAgo(3),
    lastOutboundAt: minutesAgo(46),
    lastMessage: "Tuesday after 4pm would work. How long is the consultation?",
    messages: [
      {
        id: "mock-ruth-1",
        direction: "outbound",
        body: "Hi Ruth, it is Regent Dental. Are you still interested in Invisalign?",
        aiGenerated: true,
        createdAt: minutesAgo(46),
      },
      {
        id: "mock-ruth-2",
        direction: "inbound",
        body: "Yes, I am. Tuesday after 4pm would work. How long is the consultation?",
        aiGenerated: false,
        createdAt: minutesAgo(3),
      },
    ],
  },
  {
    id: "mock-fatima",
    practiceId: "mock-practice",
    name: "Fatima Adebukola",
    phone: "+447700900456",
    email: "fatima@example.com",
    treatment: "implants",
    status: "staff_review",
    source: "boxly",
    sourceSystem: "regent",
    boxName: "Implants",
    boxStage: "Needs human",
    needsHuman: true,
    aiConfidence: 0.46,
    aiActioned: false,
    actioned: false,
    clientReplied: true,
    unseenReplyCount: 1,
    conversationCount: 4,
    leadSummary: "Previous implant experience went badly and patient requested a call.",
    urgency: "high",
    actionedNote: "Escalate to staff before any automated reply.",
    entryPoint: "https://regentdental.co.uk/implants",
    actionedAt: null,
    aiActionedAt: null,
    becameLeadAt: minutesAgo(1800),
    lastUpdatedAt: minutesAgo(18),
    scrapedAt: minutesAgo(2),
    lastSyncedAt: minutesAgo(2),
    updatedAt: minutesAgo(18),
    lastOutboundAt: null,
    lastMessage: "I had implant surgery before and it went badly. Can someone call me?",
    messages: [
      {
        id: "mock-fatima-1",
        direction: "inbound",
        body: "I had implant surgery before and it went badly. Can someone call me?",
        aiGenerated: false,
        createdAt: minutesAgo(18),
      },
    ],
  },
  {
    id: "mock-james",
    practiceId: "mock-practice",
    name: "James Wilson",
    phone: "+447700900789",
    email: "james@example.com",
    treatment: "composites",
    status: "booked",
    source: "boxly",
    sourceSystem: "regent",
    boxName: "Composite bonding",
    boxStage: "Booked",
    needsHuman: false,
    aiConfidence: 0.91,
    aiActioned: true,
    actioned: true,
    clientReplied: true,
    unseenReplyCount: 0,
    conversationCount: 8,
    leadSummary: "Booked a composite bonding consultation.",
    urgency: "booked",
    actionedNote: "Patient accepted Thursday 10:30.",
    entryPoint: "https://regentdental.co.uk/composite-bonding",
    actionedAt: minutesAgo(62),
    aiActionedAt: minutesAgo(62),
    becameLeadAt: minutesAgo(2880),
    lastUpdatedAt: minutesAgo(55),
    scrapedAt: minutesAgo(2),
    lastSyncedAt: minutesAgo(2),
    updatedAt: minutesAgo(55),
    lastOutboundAt: minutesAgo(62),
    lastMessage: "Great, booked for Thursday at 10:30.",
    messages: [
      {
        id: "mock-james-1",
        direction: "outbound",
        body: "We have Thursday 10:30 or Friday 14:00 for a composite bonding consultation.",
        aiGenerated: true,
        createdAt: minutesAgo(62),
      },
      {
        id: "mock-james-2",
        direction: "inbound",
        body: "Thursday 10:30 please.",
        aiGenerated: false,
        createdAt: minutesAgo(56),
      },
    ],
  },
];

export const mockDentalDashboardData: DentalDashboardData = {
  source: "mock",
  practiceId: "mock-practice",
  practice: {
    id: "mock-practice",
    name: "Regent Dental",
    websiteUrl: "https://regentdental.co.uk",
    location: "London",
    phone: "+442000000000",
    sourceSystem: "regent",
    whatsappStatus: "not_connected",
    connectedNumber: null,
    wasupInstanceId: null,
  },
  metrics: {
    leadTotal: mockDentalLeads.length,
    filteredLeadTotal: mockDentalLeads.length,
    loadedLeadCount: mockDentalLeads.length,
    aiActionedTotal: mockDentalLeads.filter((lead) =>
      lead.messages.some((message) => message.aiGenerated),
    ).length,
    needsHumanTotal: mockDentalLeads.filter((lead) => lead.needsHuman).length,
    bookedTotal: mockDentalLeads.filter((lead) => lead.status === "booked").length,
    clientRepliedTotal: mockDentalLeads.filter((lead) => lead.clientReplied).length,
    urgentTotal: 1,
    reactivationTotal: 2,
    todayTotal: 3,
  },
  pageInfo: {
    limit: mockDentalLeads.length,
    offset: 0,
    hasMore: false,
  },
  facets: {
    boxes: ["Invisalign", "Implants", "Composite bonding"],
    stages: ["AI actioned", "Needs human", "Booked"],
    statuses: ["engaged", "staff_review", "booked"],
  },
  laneSummary: [
    { name: "Invisalign", total: 1, needsHuman: 0, aiActioned: 1, booked: 0 },
    { name: "Implants", total: 1, needsHuman: 1, aiActioned: 0, booked: 0 },
    { name: "Composite bonding", total: 1, needsHuman: 0, aiActioned: 1, booked: 1 },
  ],
  analytics: {
    treatmentBreakdown: [
      { key: "invisalign", label: "Invisalign", total: 1, aiActioned: 1, booked: 0 },
      { key: "implants", label: "Implants", total: 1, aiActioned: 0, booked: 0 },
      { key: "composites", label: "Composite bonding", total: 1, aiActioned: 1, booked: 1 },
    ],
    sourceBreakdown: [
      { source: "boxly", total: 3, clientReplied: 3 },
    ],
    timeline: [
      { label: "Today", total: 3, aiActioned: 2, clientReplied: 3 },
    ],
    reactivation: { contacted: 2, responded: 1, booked: 1 },
    needsAttention: [
      { id: "mock-1", name: "Aisha Khan", phone: "+447900000001", treatment: "implants", urgency: "urgent", occurredAt: minutesAgo(30) },
      { id: "mock-2", name: "Tom Reilly", phone: "+447900000002", treatment: "invisalign", urgency: "reactivation", occurredAt: minutesAgo(120) },
    ],
  },
  leads: mockDentalLeads,
  integrations: [
    {
      id: "mock-boxly",
      sourceSystem: "boxly",
      displayName: "Boxly lanes",
      status: "connected",
      mode: "legacy_mirror",
      lastSyncedAt: minutesAgo(2),
      healthLabel: "Synced 2 min ago",
    },
    {
      id: "mock-dentally",
      sourceSystem: "dentally",
      displayName: "Dentally booking",
      status: "draft",
      mode: "native",
      lastSyncedAt: null,
      healthLabel: "Not connected",
    },
    {
      id: "mock-stripe",
      sourceSystem: "stripe",
      displayName: "Stripe Connect",
      status: "draft",
      mode: "native",
      lastSyncedAt: null,
      healthLabel: "Not connected",
    },
  ],
  workflows: [],
  activity: [
    {
      id: "activity-1",
      title: "Patient replied",
      description: "Ruth Derham asked about consultation length.",
      createdAt: "3 min ago",
      occurredAt: minutesAgo(3),
      leadId: "mock-ruth",
      patientName: "Ruth Derham",
      treatment: "invisalign",
      lane: "Invisalign",
      stage: "AI actioned",
      leadSummary: "Asked about Invisalign consultation availability.",
      actionedNote: "AI re-engagement sent and patient replied with availability.",
      aiActioned: true,
      clientReplied: true,
      needsHuman: false,
      conversationCount: 12,
    },
    {
      id: "activity-2",
      title: "Human review needed",
      description: "Fatima Adebukola should be called by staff.",
      createdAt: "18 min ago",
      occurredAt: minutesAgo(18),
      leadId: "mock-fatima",
      patientName: "Fatima Adebukola",
      treatment: "implants",
      lane: "Implants",
      stage: "Needs human",
      leadSummary: "Previous implant experience went badly and patient requested a call.",
      actionedNote: "Escalate to staff before any automated reply.",
      aiActioned: false,
      clientReplied: true,
      needsHuman: true,
      conversationCount: 4,
    },
    {
      id: "activity-3",
      title: "Booked",
      description: "James Wilson accepted Thursday 10:30.",
      createdAt: "55 min ago",
      occurredAt: minutesAgo(55),
      leadId: "mock-james",
      patientName: "James Wilson",
      treatment: "composites",
      lane: "Composite bonding",
      stage: "Booked",
      leadSummary: "Booked a composite bonding consultation.",
      actionedNote: "Patient accepted Thursday 10:30.",
      aiActioned: true,
      clientReplied: true,
      needsHuman: false,
      conversationCount: 8,
    },
  ],
  sourceHealth: {
    status: "mock",
    label: "Demo data",
    detail: "Connect your practice systems to keep live lead data up to date.",
    lastSyncedAt: null,
  },
};
